project_id = "nwjiyfvaoogevqovnyon"

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.sentry-tunnel]
verify_jwt = false
